VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ADODBtest"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Const adOpenDynamic = 2
Const adLockOptimistic = 3
Const adSchemaTables = 20
'(&H14)
Const adSchemaColumns = 4

Public Function Connection()

End Function

Public Function Recordset()

End Function
